run:
  # timeout for analysis
  deadline: 4m

linters-settings:
  govet:
    # Don't report about shadowed variables
    check-shadowing: false
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  whitespace:
    multi-func: true
    multi-if: true
  tagliatelle: 
    case:
      rules:
        json: snake

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gosec
    - funlen
    - maligned
    - varnamelen
    - wrapcheck
    - testpackage
    - gomnd
    - goerr113
    - exhaustruct
    
    # deprecated
    - interfacer
    - scopelint
    - golint
    - exhaustivestruct

issues:
  exclude-rules:
    - path: cmd/chantools
      linters:
        - lll